# Generated by Django 4.2.1 on 2023-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('uid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=300)),
                ('schedule', models.DateTimeField()),
                ('description', models.TextField()),
                ('files', models.ImageField(upload_to='images')),
                ('moderator', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('rigor_rank', models.IntegerField()),
                ('attendees', models.CharField(max_length=500)),
            ],
        ),
    ]
